//Common
export const GET_REG_VALUE = 'GET_VALUE'
export const GET_LOGIN_VALUE = 'GET_LOGIN_VALUE'
export const TOAST_SHOW = 'TOAST_SHOW'
export const TOAST_HIDE = 'TOAST_HIDE'
export const GET_LOGIN_INITSTATE = 'GET_LOGIN_INITSTATE'
export const SHOW_THUMBNAIL = 'SHOW_THUMBNAIL'


